In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randn(100)

In [5]:
A

array([-0.04838847, -0.30717977,  0.91585826,  1.0532265 , -0.32166606,
        0.60797689, -0.22573419, -0.38081888,  0.17093874, -0.34482194,
       -0.76275734,  0.26033355, -0.82635097,  0.56475927, -0.93751829,
       -0.63515482,  2.50253636,  1.17268756,  0.7636774 , -1.36137579,
       -0.18412924, -1.6456694 , -0.26450457, -0.20474494, -0.31892218,
        0.797579  ,  0.55588327,  0.08732924,  1.58011291, -1.12325518,
        0.49141475,  0.65796218, -2.73665699, -0.72638016,  1.09901361,
        0.2755296 ,  1.50676715,  0.28425627, -1.1361855 ,  0.80627055,
        0.7044814 , -0.40924704,  0.83179533, -0.77430336, -0.38622201,
        0.05310483,  0.73567805, -0.10258061, -0.5147751 ,  0.04896471,
       -0.55744989, -1.4871987 ,  1.09081976, -1.52336536,  0.13110341,
        1.10415834,  0.22341097,  0.20202681,  0.54861772, -0.62243419,
        0.12597755,  0.24409538, -0.51702682,  0.93665659,  0.49339989,
       -0.43075962,  0.2687926 ,  0.75122977,  1.8538647 ,  1.26

In [7]:
#平均值變50 標準差變10
A = A*50+10

In [8]:
A

array([   7.58057649,   -5.35898848,   55.79291281,   62.66132515,
         -6.08330311,   40.39884458,   -1.2867096 ,   -9.04094394,
         18.54693706,   -7.24109712,  -28.1378668 ,   23.01667744,
        -31.31754873,   38.23796367,  -36.87591463,  -21.75774121,
        135.12681783,   68.6343778 ,   48.18387001,  -58.06878969,
          0.79353819,  -72.28346979,   -3.22522841,   -0.23724694,
         -5.94610922,   49.87895025,   37.7941635 ,   14.36646205,
         89.00564543,  -46.16275913,   34.57073736,   42.89810885,
       -126.83284942,  -26.31900812,   64.95068037,   23.77647977,
         85.33835726,   24.21281375,  -46.809275  ,   50.31352748,
         45.22407005,  -10.46235181,   51.58976675,  -28.7151678 ,
         -9.31110065,   12.65524162,   46.78390235,    4.87096935,
        -15.73875513,   12.44823541,  -17.87249456,  -64.35993524,
         64.54098788,  -66.16826802,   16.55517054,   65.20791717,
         21.17054842,   20.10134068,   37.43088603,  -21.12170

In [11]:
#改成5X20矩陣(也就是5組20筆資料)
A.shape = (5 ,20) #shape 可使array變形

In [12]:
A

array([[   7.58057649,   -5.35898848,   55.79291281,   62.66132515,
          -6.08330311,   40.39884458,   -1.2867096 ,   -9.04094394,
          18.54693706,   -7.24109712,  -28.1378668 ,   23.01667744,
         -31.31754873,   38.23796367,  -36.87591463,  -21.75774121,
         135.12681783,   68.6343778 ,   48.18387001,  -58.06878969],
       [   0.79353819,  -72.28346979,   -3.22522841,   -0.23724694,
          -5.94610922,   49.87895025,   37.7941635 ,   14.36646205,
          89.00564543,  -46.16275913,   34.57073736,   42.89810885,
        -126.83284942,  -26.31900812,   64.95068037,   23.77647977,
          85.33835726,   24.21281375,  -46.809275  ,   50.31352748],
       [  45.22407005,  -10.46235181,   51.58976675,  -28.7151678 ,
          -9.31110065,   12.65524162,   46.78390235,    4.87096935,
         -15.73875513,   12.44823541,  -17.87249456,  -64.35993524,
          64.54098788,  -66.16826802,   16.55517054,   65.20791717,
          21.17054842,   20.10134068,   37.430

## <font color = 'blue'>reshape用法 </font>
> `reshape(m,n)` 是一種轉置函數，其中m與n代表列與行，把一組資料轉換成行列的行式

In [13]:
A.reshape(100,1)

array([[   7.58057649],
       [  -5.35898848],
       [  55.79291281],
       [  62.66132515],
       [  -6.08330311],
       [  40.39884458],
       [  -1.2867096 ],
       [  -9.04094394],
       [  18.54693706],
       [  -7.24109712],
       [ -28.1378668 ],
       [  23.01667744],
       [ -31.31754873],
       [  38.23796367],
       [ -36.87591463],
       [ -21.75774121],
       [ 135.12681783],
       [  68.6343778 ],
       [  48.18387001],
       [ -58.06878969],
       [   0.79353819],
       [ -72.28346979],
       [  -3.22522841],
       [  -0.23724694],
       [  -5.94610922],
       [  49.87895025],
       [  37.7941635 ],
       [  14.36646205],
       [  89.00564543],
       [ -46.16275913],
       [  34.57073736],
       [  42.89810885],
       [-126.83284942],
       [ -26.31900812],
       [  64.95068037],
       [  23.77647977],
       [  85.33835726],
       [  24.21281375],
       [ -46.809275  ],
       [  50.31352748],
       [  45.22407005],
       [ -10.462

In [15]:
A.reshape(4,25)

array([[   7.58057649,   -5.35898848,   55.79291281,   62.66132515,
          -6.08330311,   40.39884458,   -1.2867096 ,   -9.04094394,
          18.54693706,   -7.24109712,  -28.1378668 ,   23.01667744,
         -31.31754873,   38.23796367,  -36.87591463,  -21.75774121,
         135.12681783,   68.6343778 ,   48.18387001,  -58.06878969,
           0.79353819,  -72.28346979,   -3.22522841,   -0.23724694,
          -5.94610922],
       [  49.87895025,   37.7941635 ,   14.36646205,   89.00564543,
         -46.16275913,   34.57073736,   42.89810885, -126.83284942,
         -26.31900812,   64.95068037,   23.77647977,   85.33835726,
          24.21281375,  -46.809275  ,   50.31352748,   45.22407005,
         -10.46235181,   51.58976675,  -28.7151678 ,   -9.31110065,
          12.65524162,   46.78390235,    4.87096935,  -15.73875513,
          12.44823541],
       [ -17.87249456,  -64.35993524,   64.54098788,  -66.16826802,
          16.55517054,   65.20791717,   21.17054842,   20.10134068,
