In [2]:
#華氏= (攝氏)(9/5) + 32.
C = [37.5 , 40 , 100 , 60 , 0 , -40]
for k in C:
    print(k*9//5+32)

99.0
104
212
140
32
-40


In [7]:
F = []
for k in C:
    ff = k*9//5+32
    F.append(ff)

[99.0]
[99.0, 104]
[99.0, 104, 212]
[99.0, 104, 212, 140]
[99.0, 104, 212, 140, 32]
[99.0, 104, 212, 140, 32, -40]


In [6]:
F

[99.0, 104, 212, 140, 32, -40]

In [8]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [9]:
#array 用法
C = [37.5 , 40 , 100 , 60 , 0 , -40]

Celsius = np.array(C)

In [10]:
Celsius * 9//5+32

array([ 99., 104., 212., 140.,  32., -40.])

## <font color ='red'>Array用法</font>
### *Array可以使用類似向量運算*
#### 意思就是說原本List無法直接做運算，使用numpy內的array就可以直接做運算
>1.需`import numpy`並`np.arry(你的List)` <P>
2.接下來(你的List)就可以直接做運算
    
>```python
%matplotlib inline     #呼叫matplotlib
import numpy as np     #import numpy
import matplotlib.pyplot as plt     #import matplotlib.pyplot 繪圖
C = [37.5 , 40 , 100 , 60 , 0 , -40]     #你的List
Celsius = np.array(C)     #Celsius是攝氏的英文，在這裡是轉變為array
Celsius * 9//5+32     #直接運算
```
#### <font color = 'blue'>既然為向量 就可使用向量內積`np.dot(m,n)`</font>

In [11]:
G = np.array([80 , 90, 100])
W = np.array([0.3, 0.4, 0.3])

In [14]:
G*W

array([24., 36., 30.])

In [15]:
np.sum(G*W)

90.0

In [16]:
#向量內積 np.dot(m,n)
np.dot(G,W)

90.0

In [17]:
#計算多位同學成績
G = np.array([[85 ,95 ,100], [75 ,68 ,78], [98 ,88 ,95], [85 ,78 ,68]])
W = np.array([0.3 ,0.4 ,0.3])

In [18]:
G*W

array([[25.5, 38. , 30. ],
       [22.5, 27.2, 23.4],
       [29.4, 35.2, 28.5],
       [25.5, 31.2, 20.4]])

In [20]:
np.dot(G,W) #array 不只一維，也可以二維

array([93.5, 73.1, 93.1, 77.1])